var awardList = {
  "Medal of Honor": 'Ribbons/1.png',
  "Army Distinguished Service Cross": 'Ribbons/2.png',
  "Navy Cross": 'Ribbons/3.png',
  "Air Force Cross": 'Ribbons/4.png',
  "Coast Guard Cross": 'Ribbons/5.png',
  "Defense Distinguished Service Medal": 'Ribbons/6.png',
  "Homeland Security Distinguished Service Medal": 'Ribbons/7.png',
  "Distinguished Service Medal (Army)": 'Ribbons/8.png',
  "Navy Distinguished Service Medal": 'Ribbons/9.png',
  "Air Force Distinguished Service Medal": 'Ribbons/10.png',
  "Coast Guard Distinguished Service Medal": 'Ribbons/11.png',
  "Silver Star</option": 'Ribbons/12.png',
  "Defense Superior Service Medal": 'Ribbons/13.png',
  "Legion of Merit": 'Ribbons/14.png',
  "Distinguished Flying Cross": 'Ribbons/15.png',
  "Soldier's Medal": 'Ribbons/16.png',
  "Navy and Marine Corps Medal": 'Ribbons/17.png',
  "Airman's Medal": 'Ribbons/18.png',
  "Coast Guard Medal": 'Ribbons/19.png',
  "Bronze Star Medal": 'Ribbons/20.png',
  "Purple Heart": 'Ribbons/21.png',
  "Defense Meritorious Service Medal": 'Ribbons/22.png',
  "Meritorious Service Medal": 'Ribbons/23.png',
  "Air Medal": 'Ribbons/24.png',
  "Aerial Achievement Medal": 'Ribbons/25.png',
  "Joint Service Commendation Medal": 'Ribbons/26.png',
  "Army Commendation Medal": 'Ribbons/27.png',
  "Navy and Marine Corps Commendation Medal": 'Ribbons/28.png',
  "Air Force Commendation Medal": 'Ribbons/29.png',
  "Coast Guard Commendation Medal": 'Ribbons/30.png',
  "Joint Service Achievement Medal": 'Ribbons/31.png',
  "Army Achievement Medal": 'Ribbons/32.png',
  "Navy and Marine Corps Achievement Medal": 'Ribbons/33.png',
  "Air Force Achievement Medal": 'Ribbons/34.png',
  "Coast Guard Achievement Medal": 'Ribbons/35.png',
  "Commandant's Letter of Commendation": 'Ribbons/36.png',
  "Navy Combat Action Ribbon": 'Ribbons/37.png',
  "Coast Guard Combat Action Ribbon": 'Ribbons/38.png',
  "Air Force Combat Action Medal": 'Ribbons/39.png',
  "Army and Air Force Presidential Unit Citation": 'Ribbons/40.png',
  "Navy and Marine Corps Presidential Unit Citation": 'Ribbons/41.png',
  "Coast Guard Presidential Unit Citation": 'Ribbons/42.png',
  "Joint Meritorious Unit Award": 'Ribbons/43.png',
  "Army Valorous Unit Award": 'Ribbons/44.png',
  "Navy Unit Commendation": 'Ribbons/45.png',
  "Air Force Gallant Unit Citation": 'Ribbons/46.png',
  "Coast Guard Unit Commendation": 'Ribbons/47.png',
  "Army Meritorious Unit Commendation": 'Ribbons/48.png',
  "Navy Meritorious Unit Commendation": 'Ribbons/49.png',
  "Air Force Meritorious Unit Award": 'Ribbons/50.png',
  "Coast Guard Meritorious Unit Commendation":  51,
  "Army Superior Unit Award": 'Ribbons/52.png',
  "Air Force Outstanding Unit Award": 'Ribbons/53.png',
  "Coast Guard Meritorious Team Commendation": 'Ribbons/54.png',
  "Navy E Ribbon": 'Ribbons/55.png',
  "Air Force Organizational Excellence Award": 'Ribbons/56.png',
  "Coast Guard E Ribbon": 'Ribbons/57.png',
  "Prisoner of War Medal": 'Ribbons/58.png',
  "Army Good Conduct Medal": 'Ribbons/59.png',
  "Navy Good Conduct Medal": 'Ribbons/60.png',
  "Air Force Good Conduct Medal": 'Ribbons/61.png',
  "Marine Corps Good Conduct Medal": 'Ribbons/62.png',
  "Coast Guard Good Conduct Medal": 'Ribbons/63.png',
  "Combat Readiness Medal (Air Force)": 'Ribbons/64.png',
  "Outstanding Airman of the Year Ribbon": 'Ribbons/65.png',
  "Coast Guard Enlisted Person of the Year Ribbon": 'Ribbons/66.png',
  "Air Force Recognition Ribbon": 'Ribbons/67.png',
  "Army Reserve Components Achievement Medal": 'Ribbons/68.png',
  "Naval Reserve Meritorious Service Medal": 'Ribbons/69.png',
  "Air Reserve Forces Meritorious Service Medal": 'Ribbons/70.png',
  "Selected Marine Corps Reserve Medal": 'Ribbons/71.png',
  "Coast Guard Reserve Good Conduct Medal": 'Ribbons/72.png',
  "Armed Forces Reserve Medal": 'Ribbons/73.png',
  "Navy Expeditionary Medal": 'Ribbons/74.png',
  "Marine Corps Expeditionary Medal": 'Ribbons/75.png',
  "Army of Occupation Medal": 'Ribbons/76.png',
  "Navy Occupation Service Medal": 'Ribbons/77.png',
  "National Defense Service Medal": 'Ribbons/78.png',
  "Global War on Terrorism Service Medal": 'Ribbons/79.png',
  "Korea Defense Service Medal": 'Ribbons/80.png',
  "Armed Forces Service Medal": 'Ribbons/81.png',
  "Humanitarian Service Medal": 'Ribbons/82.png',
  "Outstanding Volunteer Service Medal": 'Ribbons/83.png',
  "Antarctica Service Medal": 'Ribbons/84.png',
  "Coast Guard Arctic Service Medal": 'Ribbons/85.png',
  "Air and Space Campaign Medal": 'Ribbons/86.png',
  "Nuclear Deterrence Operations Service Medal": 'Ribbons/87.png',
  "Armed Forces Expeditionary Medal": 'Ribbons/88.png',
  "Southwest Asia Service Medal": 'Ribbons/90.png',
  "Afghanistan Campaign Medal": 'Ribbons/92.png',
  "Iraq Campaign Medal": 'Ribbons/93.png',
  "Inherent Resolve Campaign Medal": 'Ribbons/94.png',
  "Global War on Terrorism Expeditionary Medal": 'Ribbons/95.png',
  "Navy Sea Service Deployment Ribbon": 'Ribbons/96.png',
  "Coast Guard Sea Service Ribbon": 'Ribbons/97.png',
  "Army Sea Duty Ribbon": 'Ribbons/98.png',
  "Naval Reserve Sea Service Ribbon": 'Ribbons/99.png',
  "Air Force Expeditionary Service Ribbon": 'Ribbons/100.png',
  "Navy Arctic Service Ribbon": 'Ribbons/101.png',
  "Navy and Marine Corps Overseas Service Ribbon": 'Ribbons/102.png',
  "Coast Guard Overseas Service Ribbon": 'Ribbons/103.png',
  "Air Force Overseas Short Tour Service Ribbon": 'Ribbons/104.png',
  "Air Force Overseas Long Tour Service Ribbon": 'Ribbons/105.png',
  "Army Overseas Service Ribbon": 'Ribbons/106.png',
  "Army Reserve Overseas Training Ribbon": 'Ribbons/107.png',
  "Coast Guard Restricted Duty Ribbon": 'Ribbons/108.png',
  "Coast Guard Special Operations Service Ribbon": 'Ribbons/109.png',
  "Air Force Special Duty Ribbon": 'Ribbons/110.png',
  "Air Force Longevity Service Award": 'Ribbons/111.png',
  "Navy Recruiting Service Ribbon": 'Ribbons/112.png',
  "Air Force Recruiter Ribbon": 'Ribbons/113.png',
  "Marine Corps Recruiting Ribbon": 'Ribbons/114.png',
  "Coast Guard Recruiting Service Ribbon": 'Ribbons/115.png',
  "Navy Recruit Training Service Ribbon": 'Ribbons/117.png',
  "Marine Corps Drill Instructor Ribbon": 'Ribbons/118.png',
  "Marine Corps Combat Instructor Ribbon": 'Ribbons/119.png',
  "Navy Ceremonial Guard Ribbon": 'Ribbons/120.png',
  "Marine Corps Security Guard Ribbon": 'Ribbons/121.png',
  "Army NCO Professional Development Ribbon": 'Ribbons/122.png',
  "Air Force NCO PME Graduate Ribbon": 'Ribbons/123.png',
  "Air Force Basic Military Training Honor Graduate Ribbon": 'Ribbons/124.png',
  "Coast Guard Basic Training Honor Graduate Ribbon": 'Ribbons/125.png',
  "Navy Basic Military Training Honor Graduate Ribbon": 'Ribbons/126.png',
  "Army Service Ribbon": 'Ribbons/127.png',
  "Air Force Training Ribbon": 'Ribbons/128.png',
  "Air Force Small Arms Expert Marksmanship Ribbon": 'Ribbons/129.png',
  "Coast Guard Distinguished Marksman Award": 'Ribbons/130.png',
  "Coast Guard Silver Rifle Excellence-in-Competition Award": 'Ribbons/131.png',
  "Coast Guard Bronze Rifle Excellence-in-Competition Award": 'Ribbons/132.png',
  "Navy Expert Rifleman Medal": 'Ribbons/133.png',
  "Coast Guard Expert Rifleman Medal": 'Ribbons/134.png',
  "Navy Rifle Marksmanship Ribbon with Sharpshooter Device": 'Ribbons/135.png',
  "Coast Guard Rifle Marksmanship Ribbon with Sharpshooter Device": 'Ribbons/136.png',
  "Navy Rifle Marksmanship Ribbon": 'Ribbons/137.png',
  "Coast Guard Rifle Marksmanship Ribbon": 'Ribbons/138.png',
  "Coast Guard Distinguished Pistol Shot Award": 'Ribbons/139.png',
  "Coast Guard Silver Pistol Excellence-in-Competition Award": 'Ribbons/140.png',
  "Coast Guard Bronze Pistol Excellence-in-Competition Award": 'Ribbons/141.png',
  "Navy Expert Pistol Shot Medal": 'Ribbons/142.png',
  "Coast Guard Expert Pistol Shot Medal": 'Ribbons/143.png',
  "Navy Pistol Marksmanship Ribbon with Sharpshooter Device": 'Ribbons/144.png',
  "Coast Guard Pistol Marksmanship Ribbon with Sharpshooter Device": 'Ribbons/145.png',
  "Navy Pistol Marksmanship Ribbon": 'Ribbons/146.png',
  "Coast Guard Pistol Marksmanship Ribbon": 'Ribbons/147.png',
  "Operation SideSwipe Campaign Medal": 'Ribbons/148.png',
  "BUSM-BA Conflict Medal": 'Ribbons/149.png',
  "Chairman of Joint Chiefs of Staff Service Medal": 'Ribbons/150.png',
  " Vice Chairman of Joint Chiefs of Staff Service Medal": 'Ribbons/151.png',
  "Senion Enlisted Advisor to the Chairman of Joint Chiefs of Staff Service Medal": 'Ribbons/152.png',
  "Chief of Staff of the Army Service Medal": 'Ribbons/153.png',
  "Vice Chief of Staff of the Army Service Medal": 'Ribbons/154.png',
  "Sergeant Major of the Army Service Medal": 'Ribbons/155.png',
  "Chief of Naval Operations Service Medal": 'Ribbons/156.png',
  "Vice Chief of Naval Operations Service Medal": 'Ribbons/157.png',
  "Master Chief Petty Officer of the Navy Service Medal": 'Ribbons/158.png',
  "Chief of Staff of the Air Force Service Medal": 'Ribbons/159.png',
  "Vice Chief of Staff of the Air Force Service Medal": 'Ribbons/160.png',
  "Command Master Sergeant of the Air Force Service Medal": 'Ribbons/161.png',
  "Commadant of the Marine Corps Service Medal": 'Ribbons/162.png',
  "Assistant Commadant of the Marine Corps Service Medal": 'Ribbons/163.png',
  "Sergeant Major of the Marine Corps Service Medal": 'Ribbons/164.png',
  "Defense Advanced Research Projects Agency Service Medal": /*'Ribbons/165.png'*/ null,
  "Enlisted Service Member of the Quarter Achievement Medal": /*'Ribbons/166.png'*/ null,
  "Warrant Officer of the Quarter Achievement Medal": /*'Ribbons/167.png'*/ null,
  "Officer of the Quarter Achievement Medal": /*'Ribbons/168.png'*/ null,
  "Founder's Meritorious Acheivement Medal": 'Ribbons/169.png',
  "Founder's Distinguished Service Ribbon": 'Ribbons/170.png'
};
